---
# tasks file for conf_keepalived
- name: Install keepalived
  apt: name=keepalived state=present

- name: config keepalived
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf

- name: config locales
  shell: printf 'net.ipv4.ip_nonlocal_bind=1' >> /etc/sysctl.conf

- name: restart sysctl
  shell: sysctl -p
  notify:
   - restart_keepalived

- name: start keepalived
  service: name=keepalived state=started enabled=yes
